---
- hosts: first_group
  user: root
  tasks:    
  - name: Change with pamd
    community.general.pamd:
      name: system-auth
      type: password
      control: requisite
      module_path: pam_pwquality.so
      module_arguments: 'try_first_pass local_users_only retry=3 authtok_type= reject_username enforce_for_root'
      state: updated
